name: kivoll infrastructure (prod)

services:
  worker:
    build:
      context: ../..
      dockerfile: dockerfiles/kivoll_worker/Dockerfile
      args:
        GIT_REPO: https://github.com/IgnyteX-Labs/kivoll_worker.git
        GIT_BRANCH: main
    restart: unless-stopped
    env_file:
      - ../.env.worker
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18
    env_file:
      - ../.env.admin
      - ../.env.worker
      - ../.env.api
      - ../.env.predict
    volumes:
      - pgdata:/var/lib/postgresql
      - ../common/initdb:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready",
              "-U \"$${POSTGRES_USER}\"",
              "-d \"$${POSTGRES_DB}\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
