name: Deploy database docker image
on:
  push:
    branches: [ main ]


permissions:
  contents: read
  packages: write

jobs:

  test:
    uses: ./.github/workflows/test.yml

  deploy-db-image:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Check if DB version changed
        id: version_check
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q '^db/VERSION$'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if DB version unchanged
        if: steps.version_check.outputs.changed != 'true'
        run: echo "DB version not changed. Skipping build."

      - name: Read DB version
        if: steps.version_check.outputs.changed == 'true'
        id: version
        run: |
          echo "version=$(cat db/VERSION)" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        if: steps.version_check.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.version_check.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: db
          file: db/Dockerfile
          push: true
          tags: |
            ghcr.io/ignytex-labs/kivoll_db:${{ steps.version.outputs.version }}
